# Generated by Django 4.1 on 2022-08-07 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=100, verbose_name='Libelle')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Photo')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('status', models.BooleanField(default='True', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Slider',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom_specialite', models.CharField(max_length=200, verbose_name='Nom_specialite')),
            ],
            options={
                'verbose_name': 'Specialite',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignage_photo', verbose_name='Photo')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialite', verbose_name='Specialite')),
            ],
            options={
                'verbose_name': 'Temoignage',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('date_projet', models.DateField(blank=True, max_length=100, null=True, verbose_name='Date projet')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='Url')),
                ('client', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_portfolio', to='main.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'ordering': ['-created'],
            },
        ),
    ]
