# Generated by Django 4.1 on 2022-08-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorie_slider_specialite_temoignage_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_portfolio', to='main.articlecategorie', verbose_name='Categorie'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
