# Generated by Django 4.1 on 2022-08-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_portfolio_categorie_delete_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoignage',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
