# Generated by Django 4.0.6 on 2022-09-10 10:58

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_temoignage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('icone', models.CharField(choices=[('fa-tools', 'fas fa-tools'), ('fa-laptop-code', 'fas fa-laptop-code'), ('fa-tablet-alt', 'fas fa-tablet-alt'), ('fa-book-reader', 'fas fa-book-reader'), ('fa-lightbulb', 'fas fa-lightbulb'), ('fa-map-signs', 'fas fa-map-signs'), ('fa-arrow-down', 'fas fa-arrow-down'), ('fa-box fa-fw', 'fas fa-box fa-fw'), ('fa-cogs fa-fw', 'fas fa-cogs fa-fw')], default='fa-book-reader', max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/docs')),
            ],
            options={
                'verbose_name': 'Doc',
                'verbose_name_plural': 'Docs',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('enonce', django_quill.fields.QuillField(blank=True, null=True)),
                ('corige', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('contenu', django_quill.fields.QuillField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lecon',
                'verbose_name_plural': 'Lecons',
            },
        ),
        migrations.CreateModel(
            name='SubCourseCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('statut', models.BooleanField(default=False, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('icone', models.CharField(choices=[('fa-tools', 'fas fa-tools'), ('fa-laptop-code', 'fas fa-laptop-code'), ('fa-tablet-alt', 'fas fa-tablet-alt'), ('fa-book-reader', 'fas fa-book-reader'), ('fa-lightbulb', 'fas fa-lightbulb'), ('fa-map-signs', 'fas fa-map-signs'), ('fa-arrow-down', 'fas fa-arrow-down'), ('fa-box fa-fw', 'fas fa-box fa-fw'), ('fa-cogs fa-fw', 'fas fa-cogs fa-fw')], default='fa-book-reader', max_length=200)),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categorys',
            },
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='specialite',
        ),
        migrations.DeleteModel(
            name='ArticleCategorie',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
        migrations.AddField(
            model_name='lecon',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_lecon', to='main.subcoursecategory'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_exercice', to='main.subcoursecategory'),
        ),
        migrations.AddField(
            model_name='docs',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_docs', to='main.subcoursecategory'),
        ),
    ]
