# Generated by Django 4.0.6 on 2022-09-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coursecategory_docs_exercice_lecon_subcoursecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcoursecategory',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie_subcategorie', to='main.coursecategory'),
        ),
    ]
