# Generated by Django 4.0.6 on 2022-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subcoursecategory_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
