# Generated by Django 4.0.6 on 2022-09-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lecon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='description',
        ),
    ]
