# Generated by Django 4.1 on 2022-08-05 17:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contry',
            field=django_countries.fields.CountryField(blank=True, max_length=200, null=True, verbose_name='Contry'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('licence', 'Licence'), ('master', 'Master'), ('autre', 'Autre'), ('bts', 'BTS'), ('doctorat', 'Doctorat')], null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
