# Generated by Django 4.1 on 2022-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_customuser_contry_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('autre', 'Autre'), ('licence', 'Licence'), ('bts', 'BTS'), ('master', 'Master'), ('doctorat', 'Doctorat')], null=True, verbose_name='Grade'),
        ),
    ]
