# Generated by Django 4.1 on 2022-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_customuser_email_alter_customuser_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('licence', 'Licence'), ('autre', 'Autre'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('bts', 'BTS')], null=True, verbose_name='Grade'),
        ),
    ]
