# Generated by Django 4.1 on 2022-08-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('doctorat', 'Doctorat'), ('master', 'Master'), ('bts', 'BTS'), ('autre', 'Autre'), ('licence', 'Licence')], null=True, verbose_name='Grade'),
        ),
    ]
