# Generated by Django 4.1 on 2022-08-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('bts', 'BTS'), ('licence', 'Licence'), ('autre', 'Autre'), ('master', 'Master'), ('doctorat', 'Doctorat')], null=True, verbose_name='Grade'),
        ),
    ]
