# Generated by Django 4.0.6 on 2022-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('licence', 'Licence'), ('doctorat', 'Doctorat'), ('autre', 'Autre'), ('master', 'Master'), ('bts', 'BTS')], null=True, verbose_name='Grade'),
        ),
    ]
