# Generated by Django 4.0.6 on 2022-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0012_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.TextField(blank=True, choices=[('autre', 'Autre'), ('doctorat', 'Doctorat'), ('bts', 'BTS'), ('master', 'Master'), ('licence', 'Licence')], null=True, verbose_name='Grade'),
        ),
    ]
